-- Framezy — seed script for the demo catalog
-- Run this in Supabase SQL Editor if you want to start with the same
-- placeholder products the storefront launched with, then edit/replace
-- them one by one with your own photos and pricing via Table Editor.
-- Safe to skip entirely if you'd rather start from a blank catalog.

insert into products
  (slug, name, category_slug, panels, price, compare_at, image, sizes, description, is_custom, rating, reviews)
values
  ('modern-geometric-abstract-canvas', 'Modern Geometric Abstract Canvas', 'abstract', 1, 5500, 11000, 'https://homezdecorz.com/cdn/shop/files/il_794xN.7358099582_mvc4.jpg?width=800', ARRAY['24x36in','30x40in','36x48in'], 'A clean geometric composition in warm neutrals — the kind of piece that anchors a living room without shouting for attention.', false, 4.8, 24),
  ('luxury-islamic-calligraphy-frame', 'Luxury Islamic Calligraphy Frame', 'islamic', 1, 5500, 11000, 'https://homezdecorz.com/cdn/shop/files/IMG-4031.png?width=800', ARRAY['24x36in','30x40in'], 'Textured calligraphy on museum-grade canvas, finished with a matte acrylic face for a soft glow under any light.', false, 4.9, 41),
  ('moody-oak-tree-canvas', 'Moody Oak Tree Canvas', 'abstract', 1, 5500, 11000, 'https://homezdecorz.com/cdn/shop/files/ChatGPT_Image_Jun_19_2026_07_36_36_AM.png?width=800', ARRAY['24x36in','30x40in'], 'Deep, moody tones with a single oak silhouette — quietly dramatic, built for reading corners and hallways.', false, 4.6, 11),
  ('luminous-ocean-sunset', 'Luminous Ocean Sunset', 'abstract', 1, 5500, 11000, 'https://homezdecorz.com/cdn/shop/files/IMG-3459.png?width=800', ARRAY['24x36in','30x40in'], 'Glowing gradient tones that read differently morning vs evening light — a favourite for lounges facing west.', false, 4.9, 7),
  ('cozy-reading-moment-canvas', 'Cozy Reading Moment Canvas', 'girlish', 1, 1800, 2500, 'https://homezdecorz.com/cdn/shop/files/ChatGPT_Image_Jul_12_2026_01_54_04_AM.png?width=800', ARRAY['16x20in','20x28in'], 'A warm, illustrative piece for a reading nook or bedside wall. Soft palette, no harsh lines.', false, 4.9, 18),
  ('mid-century-retro-bird-canvas', 'Mid-Century Retro Bird Canvas', 'animal', 1, 1800, 2500, 'https://homezdecorz.com/cdn/shop/files/ChatGPT_Image_Aug_8_2026_09_04_57_PM.png?width=800', ARRAY['16x20in','20x28in'], 'Retro mustard-and-teal palette with a mid-century bird motif — the print that started our whole aesthetic.', false, 4.8, 7),
  ('lucky-typography-frame', 'LUCKY Typography Frame', 'typography', 1, 2500, 5000, 'https://homezdecorz.com/cdn/shop/files/il_794xN.7714420865_n4wh.jpg?width=800', ARRAY['16x20in','20x28in'], 'Big, confident type on a warm ground. Pairs well as a single accent piece above a console table.', false, 4.9, 6),
  ('focus-minimalist-office-print', 'FOCUS Minimalist Office Print', 'typography', 1, 2500, 5000, 'https://homezdecorz.com/cdn/shop/files/il_1588xN.7065783692_prd1.jpg?width=800', ARRAY['16x20in','20x28in'], 'Black-and-white, no-nonsense typography built for a home office or study wall.', false, 4.7, 4),
  ('golden-geometric-2-panel', 'Golden Geometric — 2 Panel Set', 'panel-sets', 2, 3000, 6000, 'https://homezdecorz.com/cdn/shop/files/HD-899-Golden-Geometric-Abstrac-Wall-Art-2-Panel-Set.png?width=800', ARRAY['Set of 2 — 16x24in each'], 'Two-panel geometric set in gold and charcoal — the easiest way to fill a wide, empty wall fast.', false, 4.7, 9),
  ('luxury-golden-leaves-3-panel', 'Luxury Golden Leaves — 3 Panel Set', 'panel-sets', 3, 5000, 10000, 'https://homezdecorz.com/cdn/shop/files/HD-549-Luxury-Golden-Leaves-Art-_-3-Panel-Set_57185400-fb43-4136-92bc-bef8ade75f31.png?width=800', ARRAY['Set of 3 — 16x24in each'], 'Botanical gold-leaf linework across three panels. Our best-selling set for dining rooms.', false, 4.8, 8),
  ('equestrian-elegance-black-gold', 'Equestrian Elegance — Black & Gold Set', 'animal', 2, 3000, 6000, 'https://homezdecorz.com/cdn/shop/files/ChatGPT_Image_Aug_13_2026_02_31_35_PM.png?width=800', ARRAY['Set of 2 — 16x24in each'], 'A horse silhouette rendered in black and gold — bold, editorial, unmistakably a statement wall.', false, 4.6, 5),
  ('four-quls-colorful-harmony', 'The Four Quls — Colorful Harmony', 'kids', 1, 1800, 2500, 'https://homezdecorz.com/cdn/shop/files/FOUR_QUKS_1800x1800_616aea7f-d338-4a0f-8ae7-fabd145a7bca.jpg?width=800', ARRAY['16x20in','20x28in'], 'Bright, nursery-friendly Quls illustration — a gentle first Islamic piece for a kids'' room.', false, 4.8, 4),
  ('alhamdulillah-subhanallah-10-panel', 'Alhamdulillah Subhan Allah — 10 Panel Set', 'panel-sets', 10, 7499, 14998, 'https://homezdecorz.com/cdn/shop/files/Gemini_Generated_Image_p18354p18354p183.png?width=800', ARRAY['Set of 10 — full wall layout'], 'Our signature full-wall Islamic set. Ships with a printed hanging guide so the layout is foolproof.', false, 4.9, 5),
  ('custom-nikkah-frame', 'Custom Nikkah Frame', 'custom', 1, 2500, 5000, 'https://homezdecorz.com/cdn/shop/files/Gemini_Generated_Image_kc4ubakc4ubakc4u.png?width=800', ARRAY['16x20in','20x28in'], 'Send us your names and nikkah date — we lay it out and frame it. WhatsApp us your details after checkout.', true, 4.9, 0),
  ('blue-geometric-5-panel', 'Blue Geometric Shapes — 5 Panel Set', 'panel-sets', 5, 5500, 11000, 'https://homezdecorz.com/cdn/shop/files/Gemini_Generated_Image_4nb1294nb1294nb1.png?width=800', ARRAY['Set of 5 — full wall layout'], 'Cool-toned geometric set across five panels, built for large open-plan lounges.', false, 0, 0),
  ('retro-love-typography', 'Retro Love Typography Art', 'typography', 1, 2500, 5000, 'https://homezdecorz.com/cdn/shop/files/il_794xN.6284117625_o30d.jpg?width=800', ARRAY['16x20in','20x28in'], 'Warm retro type treatment — the print that inspired our whole homepage palette.', false, 4.7, 3)
on conflict (slug) do nothing;

insert into bundles
  (slug, name, description, product_ids, price, compare_at, image)
values
  ('gallery-wall-starter', 'Gallery Wall Starter Kit', 'Three of our best single-panel prints, curated to sit together — pick your trio at checkout.', ARRAY['mid-century-retro-bird-canvas','retro-love-typography','focus-minimalist-office-print'], 5400, 6800, 'https://homezdecorz.com/cdn/shop/files/ChatGPT_Image_Aug_8_2026_09_04_57_PM.png?width=800'),
  ('living-room-statement-set', 'Living Room Statement Set', 'One large abstract anchor piece plus a 2-panel companion — built for feature walls.', ARRAY['modern-geometric-abstract-canvas','golden-geometric-2-panel'], 7900, 10000, 'https://homezdecorz.com/cdn/shop/files/il_794xN.7358099582_mvc4.jpg?width=800'),
  ('islamic-home-bundle', 'Islamic Home Bundle', 'Our signature 10-panel Islamic set plus a kids-room Four Quls print for the nursery.', ARRAY['alhamdulillah-subhanallah-10-panel','four-quls-colorful-harmony'], 8600, 10800, 'https://homezdecorz.com/cdn/shop/files/Gemini_Generated_Image_p18354p18354p183.png?width=800')
on conflict (slug) do nothing;
