// Fallback / seed catalog. Once you add rows to the `products`, `categories`,
// and `bundles` tables in Supabase, lib/catalog.js reads from Supabase
// instead and this file is only used as a safety net (e.g. if Supabase is
// briefly unreachable, or before you've added your first real product).
//
// Demo catalog. Swap `image` URLs for your own photography before launch —
// these are hot-linked placeholders pulled from the reference site the brief
// provided, purely so the storefront isn't empty while you shoot real assets.

export const rooms = [
  { slug: "living-room", name: "Living Room" },
  { slug: "bedroom", name: "Bedroom" },
  { slug: "kids-room", name: "Kids Room" },
  { slug: "office", name: "Office" },
  { slug: "dining-room", name: "Dining Room" },
];

export const categories = [
  { slug: "islamic", name: "Islamic", blurb: "Calligraphy & ayah sets for a home that feels grounded." },
  { slug: "abstract", name: "Abstract", blurb: "Bold shapes and texture for statement walls." },
  { slug: "typography", name: "Typography", blurb: "Word-first pieces for minimal, quote-led spaces." },
  { slug: "floral", name: "Floral", blurb: "Botanical linework in warm, gallery tones." },
  { slug: "animal", name: "Animal & Horse", blurb: "Equestrian and wildlife pieces with real presence." },
  { slug: "girlish", name: "Girlish", blurb: "Soft, feminine sets for bedrooms and vanities." },
  { slug: "kids", name: "Kids Room", blurb: "Playful, nursery-safe prints." },
  { slug: "panel-sets", name: "Multi-Panel Sets", blurb: "2 to 10-panel gallery walls, framed and ready." },
  { slug: "custom", name: "Custom Frames", blurb: "Your own photos, names & nikkah dates — framed." },
];

export const products = [
  {
    id: "p1",
    room: "living-room",
    slug: "modern-geometric-abstract-canvas",
    name: "Modern Geometric Abstract Canvas",
    category: "abstract",
    panels: 1,
    price: 5500,
    compareAt: 11000,
    rating: 4.8,
    reviews: 24,
    image: "https://homezdecorz.com/cdn/shop/files/il_794xN.7358099582_mvc4.jpg?width=800",
    images: [
      "https://homezdecorz.com/cdn/shop/files/il_794xN.7358099582_mvc4.jpg?width=800",
      "https://homezdecorz.com/cdn/shop/files/il_794xN.7406019423_g1fg.jpg?width=800",
      "https://homezdecorz.com/cdn/shop/files/il_794xN.7358099866_kzbk.jpg?width=800",
      "https://homezdecorz.com/cdn/shop/files/il_794xN.7358099696_e0w9.jpg?width=800",
    ],
    features: [
      "Authentic luster-printed artwork with rich color and fine detail",
      "Strong border for durability and a clean, modern look",
      "Sturdy wooden back for long-lasting support",
      "Ready to hang — mounting hooks attached",
    ],
    sizes: ["24x36in", "30x40in", "36x48in"],
    sizePrices: { "24x36in": 5500, "30x40in": 6800, "36x48in": 8200 },
    description:
      "A clean geometric composition in warm neutrals — the kind of piece that anchors a living room without shouting for attention.",
  },
  {
    id: "p2",
    room: "living-room",
    slug: "luxury-islamic-calligraphy-frame",
    name: "Luxury Islamic Calligraphy Frame",
    category: "islamic",
    panels: 1,
    price: 5500,
    compareAt: 11000,
    rating: 4.9,
    reviews: 41,
    image: "https://homezdecorz.com/cdn/shop/files/IMG-4031.png?width=800",
    sizes: ["24x36in", "30x40in"],
    sizePrices: { "24x36in": 5500, "30x40in": 6800 },
    description: "Textured calligraphy on museum-grade canvas, finished with a matte acrylic face for a soft glow under any light.",
  },
  {
    id: "p3",
    room: "living-room",
    slug: "moody-oak-tree-canvas",
    name: "Moody Oak Tree Canvas",
    category: "abstract",
    panels: 1,
    price: 5500,
    compareAt: 11000,
    rating: 4.6,
    reviews: 11,
    image: "https://homezdecorz.com/cdn/shop/files/ChatGPT_Image_Jun_19_2026_07_36_36_AM.png?width=800",
    sizes: ["24x36in", "30x40in"],
    description: "Deep, moody tones with a single oak silhouette — quietly dramatic, built for reading corners and hallways.",
  },
  {
    id: "p4",
    room: "living-room",
    slug: "luminous-ocean-sunset",
    name: "Luminous Ocean Sunset",
    category: "abstract",
    panels: 1,
    price: 5500,
    compareAt: 11000,
    rating: 4.9,
    reviews: 7,
    image: "https://homezdecorz.com/cdn/shop/files/IMG-3459.png?width=800",
    sizes: ["24x36in", "30x40in"],
    description: "Glowing gradient tones that read differently morning vs evening light — a favourite for lounges facing west.",
  },
  {
    id: "p5",
    room: "bedroom",
    slug: "cozy-reading-moment-canvas",
    name: "Cozy Reading Moment Canvas",
    category: "girlish",
    panels: 1,
    price: 1800,
    compareAt: 2500,
    rating: 4.9,
    reviews: 18,
    image: "https://homezdecorz.com/cdn/shop/files/ChatGPT_Image_Jul_12_2026_01_54_04_AM.png?width=800",
    sizes: ["16x20in", "20x28in"],
    description: "A warm, illustrative piece for a reading nook or bedside wall. Soft palette, no harsh lines.",
  },
  {
    id: "p6",
    room: "living-room",
    slug: "mid-century-retro-bird-canvas",
    name: "Mid-Century Retro Bird Canvas",
    category: "animal",
    panels: 1,
    price: 1800,
    compareAt: 2500,
    rating: 4.8,
    reviews: 7,
    image: "https://homezdecorz.com/cdn/shop/files/ChatGPT_Image_Aug_8_2026_09_04_57_PM.png?width=800",
    sizes: ["16x20in", "20x28in"],
    description: "Retro mustard-and-teal palette with a mid-century bird motif — the print that started our whole aesthetic.",
  },
  {
    id: "p7",
    room: "living-room",
    slug: "lucky-typography-frame",
    name: "LUCKY Typography Frame",
    category: "typography",
    panels: 1,
    price: 2500,
    compareAt: 5000,
    rating: 4.9,
    reviews: 6,
    image: "https://homezdecorz.com/cdn/shop/files/il_794xN.7714420865_n4wh.jpg?width=800",
    sizes: ["16x20in", "20x28in"],
    description: "Big, confident type on a warm ground. Pairs well as a single accent piece above a console table.",
  },
  {
    id: "p8",
    room: "office",
    slug: "focus-minimalist-office-print",
    name: "FOCUS Minimalist Office Print",
    category: "typography",
    panels: 1,
    price: 2500,
    compareAt: 5000,
    rating: 4.7,
    reviews: 4,
    image: "https://homezdecorz.com/cdn/shop/files/il_1588xN.7065783692_prd1.jpg?width=800",
    sizes: ["16x20in", "20x28in"],
    description: "Black-and-white, no-nonsense typography built for a home office or study wall.",
  },
  {
    id: "p9",
    room: "living-room",
    slug: "golden-geometric-2-panel",
    name: "Golden Geometric — 2 Panel Set",
    category: "panel-sets",
    panels: 2,
    price: 3000,
    compareAt: 6000,
    rating: 4.7,
    reviews: 9,
    image: "https://homezdecorz.com/cdn/shop/files/HD-899-Golden-Geometric-Abstrac-Wall-Art-2-Panel-Set.png?width=800",
    sizes: ["Set of 2 — 16x24in each"],
    description: "Two-panel geometric set in gold and charcoal — the easiest way to fill a wide, empty wall fast.",
  },
  {
    id: "p10",
    room: "dining-room",
    slug: "luxury-golden-leaves-3-panel",
    name: "Luxury Golden Leaves — 3 Panel Set",
    category: "panel-sets",
    panels: 3,
    price: 5000,
    compareAt: 10000,
    rating: 4.8,
    reviews: 8,
    image: "https://homezdecorz.com/cdn/shop/files/HD-549-Luxury-Golden-Leaves-Art-_-3-Panel-Set_57185400-fb43-4136-92bc-bef8ade75f31.png?width=800",
    sizes: ["Set of 3 — 16x24in each"],
    description: "Botanical gold-leaf linework across three panels. Our best-selling set for dining rooms.",
  },
  {
    id: "p11",
    room: "living-room",
    slug: "equestrian-elegance-black-gold",
    name: "Equestrian Elegance — Black & Gold Set",
    category: "animal",
    panels: 2,
    price: 3000,
    compareAt: 6000,
    rating: 4.6,
    reviews: 5,
    image: "https://homezdecorz.com/cdn/shop/files/ChatGPT_Image_Aug_13_2026_02_31_35_PM.png?width=800",
    sizes: ["Set of 2 — 16x24in each"],
    description: "A horse silhouette rendered in black and gold — bold, editorial, unmistakably a statement wall.",
  },
  {
    id: "p12",
    room: "kids-room",
    slug: "four-quls-colorful-harmony",
    name: "The Four Quls — Colorful Harmony",
    category: "kids",
    panels: 1,
    price: 1800,
    compareAt: 2500,
    rating: 4.8,
    reviews: 4,
    image: "https://homezdecorz.com/cdn/shop/files/FOUR_QUKS_1800x1800_616aea7f-d338-4a0f-8ae7-fabd145a7bca.jpg?width=800",
    sizes: ["16x20in", "20x28in"],
    description: "Bright, nursery-friendly Quls illustration — a gentle first Islamic piece for a kids' room.",
  },
  {
    id: "p13",
    room: "living-room",
    slug: "alhamdulillah-subhanallah-10-panel",
    name: "Alhamdulillah Subhan Allah — 10 Panel Set",
    category: "panel-sets",
    panels: 10,
    price: 7499,
    compareAt: 14998,
    rating: 4.9,
    reviews: 5,
    image: "https://homezdecorz.com/cdn/shop/files/Gemini_Generated_Image_p18354p18354p183.png?width=800",
    sizes: ["Set of 10 — full wall layout"],
    description: "Our signature full-wall Islamic set. Ships with a printed hanging guide so the layout is foolproof.",
  },
  {
    id: "p14",
    room: "bedroom",
    slug: "custom-nikkah-frame",
    name: "Custom Nikkah Frame",
    category: "custom",
    panels: 1,
    price: 2500,
    compareAt: 5000,
    rating: 4.9,
    reviews: 0,
    image: "https://homezdecorz.com/cdn/shop/files/Gemini_Generated_Image_kc4ubakc4ubakc4u.png?width=800",
    sizes: ["16x20in", "20x28in"],
    description: "Send us your names and nikkah date — we lay it out and frame it. WhatsApp us your details after checkout.",
    isCustom: true,
  },
  {
    id: "p15",
    room: "living-room",
    slug: "blue-geometric-5-panel",
    name: "Blue Geometric Shapes — 5 Panel Set",
    category: "panel-sets",
    panels: 5,
    price: 5500,
    compareAt: 11000,
    rating: 0,
    reviews: 0,
    image: "https://homezdecorz.com/cdn/shop/files/Gemini_Generated_Image_4nb1294nb1294nb1.png?width=800",
    sizes: ["Set of 5 — full wall layout"],
    description: "Cool-toned geometric set across five panels, built for large open-plan lounges.",
  },
  {
    id: "p16",
    room: "bedroom",
    slug: "retro-love-typography",
    name: "Retro Love Typography Art",
    category: "typography",
    panels: 1,
    price: 2500,
    compareAt: 5000,
    rating: 4.7,
    reviews: 3,
    image: "https://homezdecorz.com/cdn/shop/files/il_794xN.6284117625_o30d.jpg?width=800",
    sizes: ["16x20in", "20x28in"],
    description: "Warm retro type treatment — the print that inspired our whole homepage palette.",
  },
];

export const bundles = [
  {
    id: "b1",
    slug: "gallery-wall-starter",
    name: "Gallery Wall Starter Kit",
    description: "Three of our best single-panel prints, curated to sit together — pick your trio at checkout.",
    productIds: ["p6", "p16", "p8"],
    price: 5400,
    compareAt: 6800,
    image: "https://homezdecorz.com/cdn/shop/files/ChatGPT_Image_Aug_8_2026_09_04_57_PM.png?width=800",
  },
  {
    id: "b2",
    slug: "living-room-statement-set",
    name: "Living Room Statement Set",
    description: "One large abstract anchor piece plus a 2-panel companion — built for feature walls.",
    productIds: ["p1", "p9"],
    price: 7900,
    compareAt: 10000,
    image: "https://homezdecorz.com/cdn/shop/files/il_794xN.7358099582_mvc4.jpg?width=800",
  },
  {
    id: "b3",
    slug: "islamic-home-bundle",
    name: "Islamic Home Bundle",
    description: "Our signature 10-panel Islamic set plus a kids-room Four Quls print for the nursery.",
    productIds: ["p13", "p12"],
    price: 8600,
    compareAt: 10800,
    image: "https://homezdecorz.com/cdn/shop/files/Gemini_Generated_Image_p18354p18354p183.png?width=800",
  },
];

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(slug) {
  if (!slug || slug === "all") return products;
  return products.filter((p) => p.category === slug);
}
